### ISSUE TITLE
permissions issue

### ISSUE THREAD

**Issue by phAtl13** [BoBkiNN/CustomDiscs#1]
Hi thee, I'm just wondering if there's a way to configure the plugin to allow non-op's the ability to play the music discs, I make them, being one of the owners of my server network, but players can't put the disc in to play them, it comes back with "no permission to play that disc"

**Comment by BoBkiNN** [comment]
There are no checks for permissions when inserting disc, maybe it's message from another plugin?

**Comment by phAtl13** [comment]
ok no problem, thanks for clearing that up :)
