### ISSUE TITLE
Inserting Sound Files

### ISSUE THREAD

**Issue by HiesukeKurusu** [BoBkiNN/CustomDiscs#3]
Hi, Im trying to insert mp3 files into the plugin configs so the plugin can read it, but i don't know where to put the files for that to happen. Can you tell me the pathing of where the plugin is reading from?

**Comment by BoBkiNN** [comment]
This plugin is not for files, its discs can play sounds that exists on minecraft client already, like vanilla sounds or sounds from resource packs. 
If you want to play sounds from files without any resource packs, you need some mods like SimpleVoiceChat or PlasmoVoice with addons and their bukkit plugin on server.
